server:
  port: 9093
#  port jenkins!! 8099


spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  profiles:
    active: @active.profile@

---
spring:
  profiles: "dev"


---
spring:
  profiles: "udemyHibernate"
  datasource:
    url: jdbc:postgresql://localhost:5432/udemyHibernate
    username: udemy
    password: udemy1664